#!/bin/bash

# Get the server id if BROKER_ID is set in env
if [ -z ${BROKER_ID+x} ]; 
then 
	
	broker_id=$(echo $(hostname -i) | awk -F '.' '{print $4}')
else 
	broker_id=$(echo $BROKER_ID)
fi

/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.kubernetes.properties \
			--override broker.id=${broker_id} \
			--override log.dirs=/data/kafka/broker-${broker_id}-log 