
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
  labels:
    name: kafka-broker-service
spec:
  type: NodePort
  selector:
    component: kafka-broker
  ports:
    - name: kafka-port
      protocol: TCP
      port: 9092
      targetPort: 9092
      
