
apiVersion: v1
kind: Service
metadata:
  name: kafka-zookeeper-service
  labels:
    app: kafka-zookeeper-service
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
      protocol: TCP
    - name: follower
      port: 2888
      targetPort: 2888
      protocol: TCP
    - name: leader
      port: 3888
      targetPort: 3888
      protocol: TCP
  selector:
    component: kafka-zookeeper